// request
export const REQUEST_SET_SUCCESS = 'REQUEST_SET_SUCCESS'
export const REQUEST_SET_ERROR = 'REQUEST_SET_ERROR'
export const REQUEST_SET_MESSAGE = 'REQUEST_SET_MESSAGE'
export const REQUEST_RESET_REQUEST = 'REQUEST_RESET_REQUEST'

// auth
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

// user
export const USER_FETCH_ME = 'USER_FETCH_ME'

// chats
export const CHATS_DELETE_CHATS = 'CHATS_DELETE_CHATS'
export const CHATS_FETCH_CHATS = 'CHATS_FETCH_CHATS'

// chat
export const CHAT_SET_CHAT = 'CHAT_SET_CHAT'

// messages
export const MESSAGES_FETCH_MESSAGES = 'MESSAGES_FETCH_MESSAGES'
export const MESSAGES_DELETE_MESSAGE = 'MESSAGES_DELETE_MESSAGE'
export const MESSAGES_CLEAR_MESSAGES = 'MESSAGES_CLEAR_MESSAGES'
export const MESSAGES_ADD_MESSAGE = 'MESSAGES_ADD_MESSAGE'

// users
export const USERS_SET_USERS = 'USERS_SET_USERS'
export const USERS_FIND_USERS = 'USERS_FIND_USERS'

// search
export const SEARCH_SET_SEARCH_VALUE = 'SEARCH_SET_SEARCH_VALUE'

// theme
export const THEME_SET_THEME = 'THEME_SET_THEME'

// background
export const BACKGROUND_SET_BACKGROUND = 'BACKGROUND_SET_BACKGROUND'
