// request
export const REQUEST_SET_SUCCESS = 'REQUEST_SET_SUCCESS'
export const REQUEST_SET_ERROR = 'REQUEST_SET_ERROR'
export const REQUEST_SET_MESSAGE = 'REQUEST_SET_MESSAGE'
export const REQUEST_RESET_REQUEST = 'REQUEST_RESET_REQUEST'

// user
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
